### ISSUE TITLE
Wrong data for Flamvell Grunika

### ISSUE THREAD

**Issue by SantiagoRivera92** [DawnbrandBots/yaml-yugi#194]
The DT02 print of Flamvell Grunika is a DRPR, not a DNPR.

**Comment by kevinlul** [comment]
Hi, the data is sourced from the wiki: https://yugipedia.com/wiki/Flamvell_Grunika. If that's the case, it should be corrected there. Note that the ingestion workflow is currently broken due to some changes on the wiki and I'm currently working on fixing that in #190, so any corrections on the wiki will not propagate until I'm done.
